spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://localhost:9091
#          uri: http://localhost:9090
          predicates:
            - Path=/order/*
        - id: inventory-service
          uri: http://localhost:9091
          predicates:
            - Path=/inventory/* ,/order/*
        - id: notification-service
          uri: http://localhost:9092
          predicates:
            - Path=/notification/*
      discovery:
        locator:
          enabled: true
server:
  port : 8222


